language: bash

services:
  - docker

git:
  clone: false

before_install:
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$ID_RSA_BASE64"|base64 -d > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - docker pull kwasek/docker-app-desktop-updater:latest

script:
  - docker run -ti --rm -v $PWD/.ssh:/.ssh kwasek/docker-app-desktop-updater:latest $(id -u) git@github.com:kwasek404/docker-app-desktop.git $([ ! -z $TRAVIS_BRANCH ]&&echo $TRAVIS_BRANCH||echo master)
